# Generated by Django 4.1.10 on 2023-11-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_userprofile_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
