# Generated by Django 4.1.10 on 2023-11-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_vegetarian',
        ),
    ]
