# Generated by Django 4.1.10 on 2023-12-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_foodorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='packing_present',
            field=models.CharField(max_length=3),
        ),
    ]
