# Generated by Django 4.1.10 on 2023-12-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_foodorder_packing_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='collected_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
