# Generated by Django 4.1.10 on 2023-12-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_foodorder_collected_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
