# Generated by Django 4.1.10 on 2023-12-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_foodorder_charity_inbox_foodorder_restaurant_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='charity_name',
            field=models.CharField(default='Nil', max_length=255),
        ),
    ]
