# Generated by Django 4.1.10 on 2023-12-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_foodorder_charity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='display_status',
            field=models.BooleanField(default=False),
        ),
    ]
