# Generated by Django 4.1.10 on 2023-12-19 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_foodorder_accept_reject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='order_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
